/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wenfahu_lane_droid_MainActivity */

#ifndef _Included_com_example_wenfahu_lane_droid_MainActivity
#define _Included_com_example_wenfahu_lane_droid_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wenfahu_lane_droid_MainActivity
 * Method:    process
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_wenfahu_lane_1droid_MainActivity_process
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_wenfahu_lane_droid_MainActivity
 * Method:    processOpt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_wenfahu_lane_1droid_MainActivity_processOpt
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
